name: Build covers.json

on:
  push:
    branches: [ main ]
    paths:
      - 'covers/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate covers.json with Python
        run: |
          python - <<'PY'
          import os, json, urllib.parse
          repo = os.environ['GITHUB_REPOSITORY'].split('/')[1]
          user = os.environ['GITHUB_ACTOR']
          sha  = os.environ['GITHUB_SHA']
          exts = {'.png','.jpg','.jpeg','.webp','.gif'}
          files = []
          for f in sorted(os.listdir('covers')):
              if os.path.splitext(f)[1].lower() in exts:
                  url_f = urllib.parse.quote(f)
                  files.append(f"https://{user}.github.io/{repo}/covers/{url_f}")
          data = {"covers": files, "version": sha}
          with open('covers.json','w') as fp:
              json.dump(data, fp, indent=2)
          PY

      - name: Commit covers.json
        run: |
          if [[ -n "$(git status --porcelain covers.json)" ]]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add covers.json
            git commit -m "Update covers.json"
            git push
          fi
